app:
  env: 'local' # 'local', 'dev', 'prod'
  name: 'dav-go'
  version: '1.0.0'
  caldav_prefix: 'calendars'
  carddav_prefix: 'contacts'

logger:
  log_level: 'debug'
  rollbar_env: 'dav-go'

postgres:
  pool_max: 4

grpc:
  ip: '0.0.0.0'
  port: '30000'

http:
  ip: '0.0.0.0'
  port: '8082'
  timeout: 4s
  idle_timeout: 60s
  user: 'admin'

  cors:
    debug: true
    allowed_methods:
      - "GET"
      - "PUT"
      - "HEAD"
      - "REPORT"
      - "OPTIONS"
      - "DELETE"
      - "PROPFIND"
      - "PROPPATCH"
      - "MKCOL"
      - "MKCALENDAR"
      - "COPY"
      - "MOVE"
    allow_credentials: true
    allowed_headers:
      - "Authorization"
      - "Location"
      - "Charset"
      - "Access-Control-Allow-Origin"
      - "Content-Type"
      - "Origin"
      - "Accept"
      - "Content-Length"
      - "Accept-Encoding"
      - "X-CSRF-Token"
    options_passthrough: true
    exposed_headers:
      - "Location"
      - "Authorization"
      - "Content-Disposition"
      - "Content-Type"
      - "Content-Range"
      - "Content-Language"
      - "Date"
      - "Content-Length"
      - "Content-Encoding"
      - "Dav"
      - "Etag"
      - "Last-Modified"
